### ISSUE TITLE
Bump REVM

### ISSUE THREAD

**Issue by gakonst** [ziyadedher/evm-bench#108]
Revm got a bunch of nice performance updates lately in https://github.com/bluealloy/revm/pull/283, would be nice to update the benches

**Comment by gakonst** [comment]
@ziyadedher lmk if you are planning on tackling this, else happy to do it myself!

**Comment by ziyadedher** [comment]
Thanks for the bump! Been feeling a bit under the weather last few days so this slipped through the cracks. Lemme knock this one out right now.

**Comment by ziyadedher** [comment]
Seeing ~10-12% speedups :sunglasses: which seems consistent with @bluealloy's results on `snailtracer`.

PR coming in a few minutes once the rest of the benches finish running (so it picks up updates to other packages).

**Comment by gakonst** [comment]
Sick. Amazing - thank you!

**Comment by ziyadedher** [comment]
https://github.com/ziyadedher/evm-bench/pull/115

> Worth also updating pyrevm, I'll give that a pass unless you want to.

Might be worth waiting until a release of `revm` comes out that includes the perf boost. I just pinned to main in the bench here.
