### ISSUE TITLE
Implement an `akula` runner

### ISSUE THREAD

**Issue by ziyadedher** [ziyadedher/evm-bench#27]
https://github.com/akula-bft/akula

**Comment by gakonst** [comment]
https://github.com/vorot93/evmodin
https://github.com/akula-bft/akula/tree/master/src/execution/evm

would love to see this benchmark

**Comment by ziyadedher** [comment]
Results are in the README! https://github.com/ziyadedher/evm-bench

Overall, Akula keeps up with revm (though according to my chat with rakita, revm will likely see a 20% performance bump soon). But right now, evmone 30+% faster than both of them after the most recent performance patch.
